# Basic Site Settings
locale                  : "en-US"
site_theme              : "default" 
title                   : "Charles Gatchalian | Academic Portfolio"
title_separator         : "-"
name                    : &name "Charles Gatchalian"
description             : &description "Computer Science student @ University of Houston"
url                     : "https://gat516.github.io" 
baseurl                 : "" 
repository              : "gat516/gat516.github.io"

# Site Author
author:
  avatar            : "files/profile.jpg"
  name              : "Charles Gatchalian"
  pronouns          : "he/him"
  bio               : "Computer Science Student at the University of Houston"
  location          : "Houston, TX"
  employer          : "University of Houston"
  uri               : 
  email             : "cjgatchalian0516@gmail.com"
  resume            : "files/resume.pdf"

  # Academic websites
  academia          : 
  arxiv             : 
  # googlescholar     : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep       : 
  impactstory       : 
  orcid             : 
  semantic          : 
  ssrn              : 
  pubmed            : 
  researchgate      : 
  scopus            : 
  zotero            :
